import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import { ConvexClientProvider } from "@/components/convex-client-provider";
import { JotaiProviderWrapper } from "@/components/ui/jotai-provider";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import { Modals } from "@/components/modals";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "KazSlack",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ConvexAuthNextjsServerProvider>
            <html lang="en">
                <body className={`${inter.className} antialiased`}>
                    <NuqsAdapter>
                        <ConvexClientProvider>
                            <JotaiProviderWrapper>
                                <Toaster />
                                <Modals />
                                {children}
                            </JotaiProviderWrapper>
                        </ConvexClientProvider>
                    </NuqsAdapter>
                </body>
            </html>
        </ConvexAuthNextjsServerProvider>
    );
}
